#!/usr/bin/env bash
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y ca-certificates curl git ufw docker.io docker-compose-v2
systemctl enable --now docker

rm -rf /tmp/trakora-src
git clone --depth=1 https://github.com/Jseven-sudo/marketintelli-backend.git /tmp/trakora-src
mkdir -p /opt/trakora
cp -a /tmp/trakora-src/trakora/. /opt/trakora/
cd /opt/trakora
chmod +x bootstrap.sh backup.sh

if [ ! -f .env ]; then
  umask 077
  cat > .env <<EOF
POSTGRES_PASSWORD=$(openssl rand -hex 24)
ADMIN_TOKEN=$(openssl rand -hex 32)
EOF
fi

$COMPOSE up -d --build

cat >/etc/cron.d/trakora-backup <<'EOF'
17 1 * * * root /opt/trakora/backup.sh >>/var/log/trakora-backup.log 2>&1
EOF
chmod 0644 /etc/cron.d/trakora-backup

mkdir -p /root/.ssh
chmod 700 /root/.ssh
touch /root/.ssh/authorized_keys
grep -q 'Generated By Termius' /root/.ssh/authorized_keys || echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKfXE3eX8Z5zctxGLI2dymy+OR64/lz+fF/ggq61DQ86 Generated By Termius' >> /root/.ssh/authorized_keys
sed -i '/trakora-deploy-2026-09-24/d' /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys

install -d /etc/ssh/sshd_config.d
cat >/etc/ssh/sshd_config.d/99-trakora.conf <<'EOF'
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin prohibit-password
EOF
systemctl restart ssh

ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw --force enable

echo "TRAKORA_BOOTSTRAP_OK"
$COMPOSE ps
